train_configs:
  # Device
  device: "cpu"
  # Logging and outputs
  logging_id: "Client1"
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataloader
data_configs:
  dataloader_path: "./dataloader/mnist_dataloader.py"
  dataloader_name: "get_mnist"
  dataloader_kwargs:
    num_clients: 2
    client_id: 0
    partition_strategy: "class_noniid"
    train_batch_size: 64
    test_batch_size: 64
    visualization: True
    output_dirname: "./output"
    output_filename: "visualization.pdf"

comm_configs:
  server_uri: localhost:50051
  max_message_size: 1048576

  # use_ssl: False
  # SSL configurations
  use_ssl: True
  use_authenticator: True
  root_certificate: ../src/appfl/comm/grpc/credentials/root.crt
  authenticator: NaiveAuthenticator
  authenticator_args:
    auth_token: a-secret-token
